version: "3.3"
services:
  api:
    build: ./api/
    restart: always
    volumes:
      - ./api/:/opt/project
      - /opt/project/node_modules/
    ports:
      - "5000:5000"
  client:
    depends_on:
      - api
    build: ./client/
    restart: always
    volumes:
      - ./client/:/opt/project
      - /opt/project/node_modules/
    ports:
      - "3000:3000"