@startuml

title Entity Relationship Diagram

entity User {
    id: serial
    username: varchar
    email: varchar
    password: varchar
    role: int
    created_at: datetime
    modified_at: datetime
    deleted_at: datetime
}

entity Page {
    id: serial
    user_id: integer
    title: varchar
    isBoardView: bool
    checkboxes: bool
    icon_path: varchar
    created_at: datetime
    modified_at: datetime
    deleted_at: datetime
}

entity BoardLabel {
    id: serial
    text: varchar
    page_id: integer
    order: int
    created_at: datetime
    modified_at: datetime
    deleted_at: datetime
}

entity Note {
    id: serial
    text: varchar
    media_id: integer
    page_id: integer
    board_label_id: integer
    order: int
    done: bool
    created_at: datetime
    modified_at: datetime
    deleted_at: datetime
}


entity Media {
    id: serial
    name: varchar
    path_to_file: varchar
    created_at: datetime
    deleted_at: datetime
}

entity ChangeLog{
    id: serial
    description: varchar
    user_id: int
    created_at: datetime
}

Page ||--o{ BoardLabel
Note ||--o| BoardLabel
Note ||--|{ Page
Note ||--o| Media
User ||--|{ Page
User ||--o{ ChangeLog

@enduml